spring.application.name=minikun_agent

spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://127.0.0.1:11434}
spring.ai.ollama.chat.options.model=${OLLAMA_MODEL:hf.co/llmfan46/gemma-4-E4B-it-ultra-uncensored-heretic-GGUF:Q6_K}
spring.ai.ollama.chat.options.num-ctx=${OLLAMA_NUM_CTX:16384}
spring.ai.ollama.embedding.options.model=${EMBEDDING_MODEL:nomic-embed-text}
